pipeline {
    agent {
        label 'scripts'
    }
    stages {
        stage('Docker Deploy QA') {
            agent any
            steps {
                sh 'docker --version'
            }
        }
    }
}
