pipeline {
    agent {
        label 'scripts'
    }
    stages {
        stage('Docker Deploy QA') {
            agent any
            steps {
                sh 'docker --version'
            }
        }
        stage('Maven Test') {
            agent {
                docker {
                    label 'scripts'
                    image 'maven:3.3.3'
                }
            }
            steps {
                sh 'mvn test'
            }
        }
        stage('Front-end') {
            agent {
              docker {
                label 'scripts'  // both label and image
                image 'node:7-alpine' 
              }
            }
            steps {
                sh 'node --version'
            }
        }
    }
}
